Adding nChannel parameter to the send and receive extension functions
YoYoGames/GMEXT-Steamworks pull request #65
Opened 2024-05-03 00:17 UTC by TheoryGeorgiou

Hello I am not a C++ programmer but I did my best to add the nChannel parameter from the steam works API into the corresponding extension functions, tested in my own game and it works!

Couple issues someone could improve upon, I do not know how to make the parameter optional in using YYGetInt32(), so currently if you use this extension without including the channel parameter in the steam_net_packet_send() and steam_net_packet_receive() functions it will cause an error. 

Please review, fix and commit! Thank you.

2024-05-24 12:07 UTC, DiasFranciscoA requested changes

2024-05-24 12:07 UTC, DiasFranciscoA commented on source/Steamworks_gml/extensions/steamworks/steamworks_cpp/GMLSteam/steam_networking.cpp
> +	uint32 value32 = (argc >= 0) ? YYGetInt32(arg, 4) : 0;
if you are checking for `YYGetInt32(.., 4)` you need to check if `argc > 3`

2024-05-24 12:07 UTC, DiasFranciscoA commented on source/Steamworks_gml/extensions/steamworks/steamworks_cpp/GMLSteam/steam_networking.cpp
> +	uint32 value32 = (argc >= 0) ? YYGetInt32(arg, 0) : 0;
Same as before if you are checking for `YYGetInt32(.., 0)` you need to check if `argc > 0`

2024-06-07 19:57 UTC, DiasFranciscoA commented
@TheoryGeorgiou could you please update the PR so we can merge it?

2024-06-09 00:15 UTC, TheoryGeorgiou commented
@DiasFranciscoA done!

2024-06-19 19:30 UTC, jzavala-YYG commented
"Merged" here: ad7af527a644a6ca2dbdef50ebe5f440ad01b453

2024-06-19 19:30 UTC, closed without merging